#==============================================================================
#D A make file to make the unit tests
EXECUTABLES = exe/utest_engEngine.exe exe/utest_engAI.exe
INCLUDES = -I.. -I../../dgcUtils
LIBS = ../lib/Engine.lib
RUN_TESTS = ./exe/utest_engAI.exe && ./exe/utest_engEngine.exe

include $(DROPBOX)/Coding/MakeFiles/cpp_utest.mk
