#==============================================================================
#D A make file to make an executable project


#------------------------------------------------------------------------------
# Options to edit with specific project names
EXE = engConnect_4
LIB = Engine
# OBJECTS must be in dependency order right depending on left, and preceded by
# obj/ eg obj/utility.o obj/file.o
OBJECTS = obj/engEngine.o obj/engAI.o
INCLUDES = -I. -I../dgcUtils

include $(DROPBOX)/Coding/MakeFiles/cpp.mk
